#!/bin/bash
# Install the shell configuration.
#
# This package has its own installer rather than being mirrored into $HOME,
# because zsh is not installed file by file: only ~/.zshenv is placed in $HOME,
# and it sets ZDOTDIR so zsh reads .zshrc and the rest straight out of zsh/.
# The plugin submodules and the machine-local file need handling too.
#
# Safe to re-run. Called by the top-level install.sh, or directly.

set -u

SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ZDOTDIR_SRC="$SOURCE_DIR/zsh"
STAMP="pre-zdotdir"
DRY_RUN="${DOTFILES_DRY_RUN:-0}"

if [ "$DRY_RUN" = "1" ]; then
    echo "   would link ~/.zshenv -> ${ZDOTDIR_SRC/#$HOME/~}/.zshenv"
    echo "   would initialise the zsh-async and zsh-history-substring-search submodules"
    echo "   would ensure ${XDG_CACHE_HOME:-$HOME/.cache}/zsh exists"
    [ -e "$HOME/.zsh.local" ] || echo "   would create ~/.zsh.local (mode 600)"
    exit 0
fi

echo "🚀 Installing zsh configuration from $ZDOTDIR_SRC..."

# ---------------------------------------------------------------------------
# Move aside the files ZDOTDIR makes inert.
#
# With ZDOTDIR set, zsh reads $ZDOTDIR/.zshrc and $ZDOTDIR/.zprofile and
# ignores the ones in $HOME entirely. Leaving them in place is harmless but
# deeply confusing later, so they are backed up and removed.
# ---------------------------------------------------------------------------
for f in "$HOME/.zshrc" "$HOME/.zprofile"; do
    if [ -e "$f" ] || [ -L "$f" ]; then
        if [ -e "$f.$STAMP" ]; then
            echo "   ℹ️  Backup $f.$STAMP already exists, leaving it alone"
            rm -f "$f"
        else
            mv "$f" "$f.$STAMP"
            echo "   ✅ Backed up $(basename "$f") -> $(basename "$f").$STAMP"
        fi
    fi
done

# ---------------------------------------------------------------------------
# The one symlink. On MSYS2/Cygwin, symlink creation needs Developer Mode or
# admin, so fall back to a small real file that does the same job.
# ---------------------------------------------------------------------------
ZSHENV="$HOME/.zshenv"
if [ -L "$ZSHENV" ] && [ "$(readlink "$ZSHENV")" = "$ZDOTDIR_SRC/.zshenv" ]; then
    echo "   ℹ️  ~/.zshenv already points here"
elif [ -e "$ZSHENV" ] || [ -L "$ZSHENV" ]; then
    rm -f "$ZSHENV"
fi

if [ -e "$ZSHENV" ] || [ -L "$ZSHENV" ]; then
    : # already correct, handled above
elif ln -s "$ZDOTDIR_SRC/.zshenv" "$ZSHENV" 2>/dev/null; then
    echo "   ✅ Linked ~/.zshenv -> $ZDOTDIR_SRC/.zshenv"
else
    cat > "$ZSHENV" <<EOF
# Generated by install.sh because this system could not create a symlink.
# Re-run install.sh after moving the repository.
ZDOTDIR="$ZDOTDIR_SRC"
source "\$ZDOTDIR/.zshenv"
EOF
    echo "   ✅ Wrote ~/.zshenv (symlinks unavailable; using a real file)"
fi

# ---------------------------------------------------------------------------
# Plugins
# ---------------------------------------------------------------------------
# Restricted to our two plugins by pathspec. Without it, git walks every
# submodule in the enclosing repository, and an unrelated broken gitlink
# elsewhere in the tree aborts the whole run.
if command -v git >/dev/null 2>&1 && git -C "$SOURCE_DIR" rev-parse --git-dir >/dev/null 2>&1; then
    if git -C "$SOURCE_DIR" submodule update --init -- \
            zsh/plugins/zsh-async zsh/plugins/zsh-history-substring-search; then
        echo "   ✅ Plugin submodules initialised"
    else
        echo "   ❌ Failed to initialise submodules; plugins will be skipped at startup"
    fi
else
    echo "   ℹ️  Not a git checkout, skipping submodule init"
fi

# ---------------------------------------------------------------------------
# Cache directory
# ---------------------------------------------------------------------------
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
mkdir -p "$CACHE_DIR" && echo "   ✅ Cache directory: $CACHE_DIR"

# ---------------------------------------------------------------------------
# Machine-local file: identity and secrets. Never tracked, and deliberately
# outside the repository so it cannot be committed by accident.
# ---------------------------------------------------------------------------
LOCAL_FILE="$HOME/.zsh.local"
if [ -e "$LOCAL_FILE" ]; then
    echo "   ℹ️  $LOCAL_FILE already exists, leaving it untouched"
else
    cat > "$LOCAL_FILE" <<EOF
# Machine-local zsh configuration. NOT tracked in git -- put secrets here.
# Sourced first by conf.d/05-environment.zsh, before the os/ and hosts/ layers.

# Selects hosts/<name>.zsh. Set explicitly because a DHCP-assigned hostname
# changes between networks.
ZSH_MACHINE=$(scutil --get LocalHostName 2>/dev/null || hostname -s 2>/dev/null || echo "${HOSTNAME%%.*}")

# export SOME_SECRET='...'
EOF
    chmod 600 "$LOCAL_FILE"
    echo "   ✅ Created $LOCAL_FILE (mode 600)"
fi

echo "✨ Installation complete!"
echo "-------------------------------------------------------"
if [ -e "$HOME/.zprofile.$STAMP" ]; then
    echo "⚠️  ACTION REQUIRED: your old ~/.zprofile held secrets."
    echo "   Copy any 'export ...' secret lines from"
    echo "     $HOME/.zprofile.$STAMP"
    echo "   into"
    echo "     $LOCAL_FILE"
    echo "   Machine paths and Homebrew setup are already handled by conf.d/, os/ and hosts/."
    echo ""
fi
echo "Open a NEW terminal to pick up the changes. Keep this one open until"
echo "you have confirmed the new shell works."
echo ""
echo "To roll back:"
echo "   rm ~/.zshenv"
echo "   mv ~/.zshrc.$STAMP ~/.zshrc         # if present"
echo "   mv ~/.zprofile.$STAMP ~/.zprofile   # if present"
echo "-------------------------------------------------------"
