#!/bin/bash

set -u

PKG_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$PKG_DIR/../install-lib.sh"

ZDOTDIR_SRC="$PKG_DIR/zsh"
LOCAL_FILE="$HOME/.shell.local"

# Move aside the zsh files ZDOTDIR makes inert.
backup_file "$HOME/.zshrc";    ZSHRC_BAK="$DOTFILES_LAST_BACKUP"
backup_file "$HOME/.zprofile"; ZPROFILE_BAK="$DOTFILES_LAST_BACKUP"

# On MSYS2/Cygwin, symlink creation needs Developer Mode or admin, so fall back
# to a small real file that does the same job. Never a plain copy: zsh/.zshenv
# derives ZDOTDIR from its own resolved path, so a copy sitting in $HOME would
# point ZDOTDIR at $HOME and load nothing from this repository.
link_home --no-copy "$ZDOTDIR_SRC/.zshenv"
case $? in
    0) ;;
    1)
        # Absolute, unlike the symlink: zsh sources this file without resolving
        # where it came from, so a relative ZDOTDIR would be read against the cwd.
        write_file "$HOME/.zshenv" <<EOF
# Generated by install.sh because this system could not create a symlink.
# Re-run install.sh after moving the repository.
ZDOTDIR="$ZDOTDIR_SRC"
source "\$ZDOTDIR/.zshenv"
EOF
        ;;
    *) exit 1 ;;
esac

# .bash_profile is needed as well as .bashrc: bash reads only the profile for
# login shells, and macOS Terminal opens a login shell for every tab.
link_home "$PKG_DIR/bash/.bashrc"
link_home "$PKG_DIR/bash/.bash_profile"

# When run on its own, note any plugin submodule that is missing. A hint rather
# than a failure: conf.d/40-plugins skips what it cannot find.
for d in "$ZDOTDIR_SRC"/plugins/*/; do
    [ -d "$d" ] || continue
    if [ -z "$(ls -A "$d" 2>/dev/null)" ]; then
        echo "   ℹ️  $(basename "$d") is empty -- run the top-level ./install.sh to check out submodules"
    fi
done

# One per shell. See cached_eval in shared/lib.sh.
CACHE_ROOT="${XDG_CACHE_HOME:-$HOME/.cache}"
ensure_dir "$CACHE_ROOT/zsh" "$CACHE_ROOT/bash"

write_file --no-clobber "$LOCAL_FILE" 600 <<EOF
# Machine-local shell configuration. NOT tracked in git -- put secrets here.
# Read by BOTH bash and zsh, so keep it compatible with both.

# Loads the machine specific settings from shared/hosts/<name>.sh.
SHELL_MACHINE=$(scutil --get LocalHostName 2>/dev/null || hostname -s 2>/dev/null || echo "${HOSTNAME%%.*}")

# export SOME_SECRET='...'
EOF

# Nothing below applies to a run that changed nothing: the shell in this
# terminal is already the installed one, so there is no new terminal to open and
# nothing to roll back.
if [ "$DOTFILES_DRY_RUN" = 1 ] || [ "$DOTFILES_CHANGED" = 0 ]; then
    exit "$DOTFILES_FAILED"
fi

echo "-------------------------------------------------------"
if [ -n "$ZSHRC_BAK" ] || [ -n "$ZPROFILE_BAK" ]; then
    echo "⚠️  ACTION REQUIRED: zsh no longer reads ~/.zshrc or ~/.zprofile, because"
    echo "   ZDOTDIR now points at this repository. These were moved aside:"
    [ -n "$ZSHRC_BAK" ]    && echo "     $ZSHRC_BAK"
    [ -n "$ZPROFILE_BAK" ] && echo "     $ZPROFILE_BAK"
    echo "   Review them and move anything you still need -- secrets especially --"
    echo "   into"
    echo "     $LOCAL_FILE"
    echo "   Machine paths and Homebrew setup are already handled by conf.d/, os/ and hosts/."
    echo ""
fi
echo "Open a NEW terminal to pick up the changes. Keep this one open until"
echo "you have confirmed the new shell works."
echo ""
echo "To roll back:"
echo "   rm ~/.zshenv ~/.bashrc ~/.bash_profile"
[ -n "$ZSHRC_BAK" ]    && echo "   mv $ZSHRC_BAK ~/.zshrc"
[ -n "$ZPROFILE_BAK" ] && echo "   mv $ZPROFILE_BAK ~/.zprofile"
echo "-------------------------------------------------------"

exit "$DOTFILES_FAILED"
